# This is a basic workflow to help you get started with Actions

name: TESTANDO

# Controls when the workflow will run
on:  
  workflow_dispatch:

jobs:  
  build:    
    runs-on: ubuntu-latest    
    steps:      
      - uses: actions/checkout@v3      
      - name: Run a one-line script
        run: echo Hello, world!
  DEV:    
    runs-on: ubuntu-latest
    environment:
      name: DEV
      url: 'blunatrostdorf.com'
    needs: build
    steps:       
    
      - name: Run a one-line script2
        run: echo AMBIENTE DEV
  HOMOL:    
    runs-on: ubuntu-latest
    environment:
      name: homol
      url: 'blunatrostdorf.com'
    needs: DEV
    steps:       
    
      - name: Run a one-line script2
        run: echo AMBIENTE HOMOL
